### ISSUE TITLE
Kubernetes 1.22 compatibility

### ISSUE THREAD

**Issue by xavierbaude** [DataDog/watermarkpodautoscaler#135]
It seems that K8s 1.22 is not compatible with WPA since your CRDs still use v1beta1 `apiVersion: apiextensions.k8s.io/v1beta1`

Link: [CRD](https://github.com/DataDog/watermarkpodautoscaler/blob/main/chart/watermarkpodautoscaler/templates/datadoghq.com_watermarkpodautoscalers_crd.yaml#L1)

link to Kubernetes documentation:
[Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122)

**Comment by xavierbaude** [comment]
Any update on this? 1.22 release is the next "STABLE" release for some cloud providers.

**Comment by CharlyF** [comment]
Apologies for the delay, I am on it.

**Comment by cforce** [comment]
ping -also waiting..

**Comment by CharlyF** [comment]
Hi @cforce - I made a PR (#143) that should fix this. I will merge it tomorrow (I wanted to give a chance to the initial contributor to make sure it would work for them).
