### ISSUE TITLE
WPA doesn't build on M1

### ISSUE THREAD

**Issue by iksaif** [DataDog/watermarkpodautoscaler#159]
* `hack/install-wwhrd.sh` fails to install an ARM64 version (the amd64 version works, there's probably a new release as well)
* `hack/install-yq.sh` fails to install an ARM64 version (the amd64 version works, we need to move to yq 4 to have an arm64 version)
* We need `go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0` instead of `go get`
* etcd is not installed by `install-tools` but required for the tests
* `hack/install-kubebuilder.sh` only copy the kubebuilder binary and forgets the assets (etcd/kube-apiserver). Downloading the amd64 version and replacing etcd by an arm64 version works
* `make e2e` doesn't work, the pod says `runtime: failed to create new OS thread (have 2 already; errno=22)`

**Comment by clamoriniere** [comment]
This issue is now solved
