### ISSUE TITLE
Standby pods are panicking

### ISSUE THREAD

**Issue by ferrous26** [DataDog/watermarkpodautoscaler#77]
**Describe what happened:**

When I run the autoscaler in HA, having a second pod in standby, the second pod will log out that it is standing by a few times and then exit. Eventually the pod enters a `CrashBackoffLoop` state, which means it will not actually be standing by part of the time.

What I see in the pod `describe` output is:

```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 17 Mar 2021 11:54:57 -0400
      Finished:     Wed, 17 Mar 2021 11:55:27 -0400
    Ready:          False
    Restart Count:  3258
```

What I see in the logs:

```
{"level":"info","ts":1615997228.2988877,"logger":"cmd","msg":"Version: v0.2.0-dirty"}
{"level":"info","ts":1615997228.2989118,"logger":"cmd","msg":"Build time: 2020-09-09/20:03:05"}
{"level":"info","ts":1615997228.2989151,"logger":"cmd","msg":"Git tag: v0.2.0"}
{"level":"info","ts":1615997228.298917,"logger":"cmd","msg":"Git Commit: 3c5176693cdf2838c54298fb6f732c4ac21dbe86"}
{"level":"info","ts":1615997228.2989194,"logger":"cmd","msg":"Go Version: go1.13.15"}
{"level":"info","ts":1615997228.2989216,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1615997228.2989237,"logger":"cmd","msg":"Version of operator-sdk: v0.13.0"}
{"level":"info","ts":1615997228.299064,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1615997229.3133864,"logger":"leader","msg":"Found existing lock","LockOwner":"watermarkpodautoscaler-69cc854fbf-dqjbg"}
{"level":"info","ts":1615997229.3252141,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1615997230.456776,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1615997232.8421242,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1615997237.3827972,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1615997246.0937243,"logger":"leader","msg":"Not the leader. Waiting."}
```

**Describe what you expected:**

I expect that the pod can remain online and continue to check if it can become leader without panicking.

**Steps to reproduce the issue:**

- Run 2 or more autoscaler pods in the same cluster, with leader election enabled
- Wait a few minutes
- Check on standby pod state

**Additional environment details (Kubernetes version, etc):**

Autoscaler image: `datadog/watermarkpodautoscaler:v0.2.0`, exact commit hash is in the logs above

I'm seeing this behaviour in multiple clusters, different kubernetes versions:

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}                              
```

```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by CharlyF** [comment]
Hey there!
We fixed this in the new minor version of the controller (0.3.0) that should be released in the next few days.
See [here](https://github.com/DataDog/watermarkpodautoscaler/pull/71) and [here](https://github.com/DataDog/watermarkpodautoscaler/pull/74).

I will close this for now, feel free to reach out if you face any more issues!
