### ISSUE TITLE
host images in docker hub

### ISSUE THREAD

**Issue by cforce** [DataDog/watermarkpodautoscaler#93]
"docker.io/datadog/watermarkpodautoscaler:v0.3.0-rc5": failed to resolve
          reference "docker.io/datadog/watermarkpodautoscaler:v0.3.0-rc5": docker.io/datadog/watermarkpodautoscaler:v0.3.0-rc5:

**Comment by clamoriniere** [comment]
Hello @cforce 

I think a `.` is missing on the image tag (between `rc` and `5`)

I just tested: `docker pull datadog/watermarkpodautoscaler:v0.3.0-rc.5` and it seams to work.

Also `rc.6` is out :)

please let me know if it solved your issue.

Cedric

**Comment by cforce** [comment]
That is true, but would propose you fix it in your repo where the  bug is introduced https://github.com/DataDog/watermarkpodautoscaler/blob/v0.3.0-rc.5/chart/watermarkpodautoscaler/values.yaml
https://github.com/DataDog/watermarkpodautoscaler/blob/v0.3.0-rc.6/chart/watermarkpodautoscaler/values.yaml
![image](https://user-images.githubusercontent.com/393286/121070109-9a3fe080-c7ce-11eb-8926-f0242416bd02.png)

**Comment by clamoriniere** [comment]
good catch I will fix in the #95 PR

**Comment by clamoriniere** [comment]
should be fixed now
