### ISSUE TITLE
watermarkpodautoscaler": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by cforce** [DataDog/watermarkpodautoscaler#94]
21s         Warning   Failed             pod/watermarkpodautoscaler-66d6d96c96-9ms4b    Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "watermarkpodautoscaler": executable file not found in $PATH: unknown

**Comment by clamoriniere** [comment]
Thanks for opening this issue,

I have open this PR #95 that should solve the issue.
I suppose you are trying to test the `v0.3-rc.X` version. This fix is on the v0.3 branch so you need to deploy the controller with the chart from this branch too.

When the release will be finalised we will pull back all the change to the `main` branch.

**Comment by clamoriniere** [comment]
should be fixed thanks to #95
