### ISSUE TITLE
crash loop - flag provided but not defined: -zap-level

### ISSUE THREAD

**Issue by cforce** [DataDog/watermarkpodautoscaler#97]
Seems like used container params are unknown to the container/ go application

 kubectl logs watermarkpodautoscaler-75cd69b9f7-tz88b
```
flag provided but not defined: -zap-level
Usage of /manager:
  -enable-leader-election
        Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager. (default true)
  -health-port int
        Port to use for the health probe (default 9440)
  -kubeconfig string
        Paths to a kubeconfig. Only required if out-of-cluster.
  -leader-election-resource string
        determines which resource lock to use for leader election. option:[configmapsleases|endpointsleases|configmaps] (default "configmaps")
  -logEncoder string
        log encoding ('json' or 'console') (default "json")
  -loglevel value
        Set log level
  -metrics-addr string
        The address the metric endpoint binds to. (default ":8080")
  -syncPeriodSeconds int
        The informers resync period in seconds (default 3600)
  -version
        print version and exit
```

**Comment by clamoriniere** [comment]
Hello again :)

this PR #96 created earlier will solve the issue. I'm waiting a review to merge it

**Comment by cforce** [comment]
You shall remove or move the CHANGELOG.md  from or away from the chart folder https://github.com/DataDog/watermarkpodautoscaler/blob/clamoriniere/improve-release-process/chart/watermarkpodautoscaler/templates/. Helm does have problems as it tries to parse and resolve.

**Comment by clamoriniere** [comment]
@cforce thanks for the info.

We merge #95 and moved the `CHANGELOG.md` file to the root folder of the chart.

I just tested from the `v0.3` branch with `helm install wpa chart/watermarkpodautoscaler --set image.tag=v0.3.0-rc.6` command, and it works on my side.

Please let me know how it went on your side, and how your WPA tests goes.

**Comment by cforce** [comment]
It does as well there. I will let you now if further

**Comment by cforce** [comment]
Went well here too. Will let you know if further findings. Tx so far.
